/*** AUTOGENERATED FILE - DO NOT EDIT DIRECTLY ***/

(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";

var renderer = require('./lib/renderer'),
    Templatist = {};

renderer(Templatist);

module.exports = Templatist;

// Define for amd
window.define('nodebb-templatist', function() {
    return Templatist;
});


},{"./lib/renderer":2}],2:[function(require,module,exports){
"use strict";

module.exports = function(Templatist) {
    var templatesCache = {},
        typesCache = {},
        loaders = {},
        helpers = {},
        globals = {};

    Templatist.updateTypesCache = function(obj) {
        for (var name in obj) {
            if (obj.hasOwnProperty(name)) {
                typesCache[name] = obj[name];
            }
        }
    };

    Templatist.lookupType = function(name) {
        return typesCache[name];
    };

    function registerSomething(store, method, name, value, ext) {
        if (!ext) {
            store[name] = value;
            for (var key in loaders) {
                registerSomething(store, method, name, value, key);
            }
        }
        else {
            loaders[ext][method].call(loaders[ext], name, value);
        }
    }

    Templatist.registerLoader = function(ext, loader) {
        loaders[ext] = loader;
        var name;
        for (name in helpers) {
            Templatist.registerHelper(name, helpers[name], ext);
        }
        for (name in globals) {
            Templatist.setGlobal(name, globals[name], ext);
        }
    };

    Templatist.registerHelper = function(name, helper, ext) {
        registerSomething(helpers, 'registerHelper', name, helper, ext);
    };

    Templatist.setGlobal = function(name, value, ext) {
        registerSomething(globals, 'setGlobal', name, value, ext);
    };

    Templatist.load = function(name, callback) {
        if (templatesCache[name]) {
            callback(null, templatesCache[name]);
            return;
        }

        var ext = Templatist.lookupType(name);
        if (!ext) {
            callback(new Error('Can\'t determine template type: ' + name));
            return;
        }

        if (!loaders[ext]) {
            callback(new Error('Loader not found for extension ' + ext));
            return;
        }

        try {
            loaders[ext](name, function(err, render) {
                if (err) {
                    callback(err);
                    return;
                }

                templatesCache[name] = render;
                callback(null, render);
            });
        } catch (err) {
            callback(err);
        };
    };

    Templatist.render = function(name, block, data, callback) {
        if (typeof data == 'function' && typeof callback == 'undefined') {
            callback = data;
            data = null;
        }

        if (typeof block == 'object') {
            data = block;
            block = '';
        }

        if (typeof name != 'string'
            || typeof block != 'string'
            || typeof data != 'object'
            || typeof callback != 'function') {
            console.log("[Templatist warning] render arguments looks wrong: " + arguments);
        }

        Templatist.load(name, function(err, render) {
            if (err) {
                callback(err);
                return;
            }

            try {
                render(name, block, data, callback);
            } catch (err) {
                callback(err);
            }
        });
    };

    Templatist.flush = function() {
        templatesCache = {};
    };
};


},{}]},{},[1]);
